In [1]:
import geopandas as gpd

In [9]:
gdf = gpd.read_file("/home/jovyan/work/my_scripts/afghan_imgs_shp.gpkg")

In [10]:
gdf

,path,geometry
0,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((64.11997 29.77251, 64.11997 29.78228..."
1,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((63.19369 30.10525, 63.19369 30.11505..."
2,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((63.96709 30.25815, 63.96709 30.26792..."
3,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((63.38253 30.50097, 63.38253 30.51073..."
4,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((63.49045 30.52794, 63.49045 30.53771..."
...,...,...
160,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((67.03387 32.66826, 67.03387 32.67817..."
161,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((67.10581 32.83914, 67.10581 32.84903..."
162,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((67.36662 32.85712, 67.36662 32.86702..."
163,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((66.89897 32.08370, 66.89897 32.09361..."
164,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((61.86288 30.96845, 61.86288 30.97854..."

In [11]:
gdf[gdf.geometry.duplicated(keep=False)]

,path,geometry
94,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((62.48330 30.00626, 62.48330 30.01619..."
95,/home/jovyan/work/imagery/afghanistan/train_va...,"POLYGON ((62.48330 30.00626, 62.48330 30.01619..."

In [12]:
duplicates = gdf[gdf.duplicated("geometry", keep=False)]

In [22]:
duplicates["path"].values

array(['/home/jovyan/work/imagery/afghanistan/train_validation/imgs/FID95_101_GE01_230206_1.tif',
       '/home/jovyan/work/imagery/afghanistan/train_validation/imgs/FID96_102_GE01_230206_1.tif'],
      dtype=object)

In [6]:
gdf

,fid,PageName,PageNumber,ADM0_VIZ_N,ADM1_VIZ_N,ADM2_VIZ_N,GUID,Grid_Statu,STATUS,GlobalID,...,OvertureMa,Overture_1,Shape__A_2,Shape__L_2,kmeans_clu,kmeans_cla,kmeans_lab,layer,path,geometry
0,1,AS361,14633,Afghanistan,Hilmand,Garmser,{13be73bd-022f-4a77-be7e-313554a28c5b},Grid cells that are planned but not started,0,{cbadd6cc-c095-4fa7-983e-ccc73695ae5a},...,0.000000,0.000000,1.148876e+06,4297.420693,1,0,Low,hilmand_class_1__hilmand_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((64.10999 29.77243, 64.10999 29.78236..."
1,10,GA342,90637,Afghanistan,Hilmand,Reg,{c04037ab-01a1-4be9-9187-0974ff84fe6f},Grid cells that are planned but not started,0,{d99fc882-aca5-4452-a400-4e426e4436ff},...,0.000000,0.000000,1.163716e+06,4327.068175,1,0,Low,hilmand_class_1__hilmand_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((63.93912 31.01350, 63.93912 31.02342..."
2,100,FQ107,85161,Afghanistan,Nimroz,Zaranj,{44d831f1-40a2-455c-ac4d-6a07704ce85c},Grid cells that are planned but not started,1,{dacb7ea2-0caa-4d0b-a272-b710b5517936},...,369.892417,3.736702,1.162609e+06,4324.857436,3,1,Medium,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((61.82571 30.92357, 61.82571 30.93349..."
3,101,FR110,85677,Afghanistan,Nimroz,Zaranj,{44d831f1-40a2-455c-ac4d-6a07704ce85c},Grid cells that are planned but not started,1,{1e76b9d1-1d1e-4f10-bdd8-83a23e0dd8a0},...,1862.469309,22.843910,1.162720e+06,4325.077908,1,3,Very High,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((61.85269 30.93256, 61.85269 30.94248..."
4,102,FR112,85679,Afghanistan,Nimroz,Zaranj,{44d831f1-40a2-455c-ac4d-6a07704ce85c},Grid cells that are planned but not started,1,{fea1f034-9135-46fe-aeb5-08050befd50f},...,1577.730773,17.415251,1.162720e+06,4325.078068,2,2,High,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((61.87068 30.93256, 61.87068 30.94248..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,95,BS179,29805,Afghanistan,Nimroz,Charburjak,{27045810-9142-4354-9682-fa8a0c00493b},Grid cells that are planned but not started,0,{42eaf536-402b-476e-a5f4-b2cd46aa2d21},...,0.000000,0.000000,1.151602e+06,4302.866189,0,0,Low,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((62.47323 30.00626, 62.47323 30.01619..."
159,96,CE91,36669,Afghanistan,Nimroz,Charburjak,{27045810-9142-4354-9682-fa8a0c00493b},Grid cells that are planned but not started,0,{d74511e3-8159-4c4f-aed2-e55e8bdf38a2},...,0.000000,0.000000,1.152871e+06,4305.401207,0,0,Low,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((61.68182 30.11418, 61.68182 30.12410..."
160,97,CW131,46954,Afghanistan,Nimroz,Charburjak,{27045810-9142-4354-9682-fa8a0c00493b},Grid cells that are planned but not started,1,{2516cc73-73ab-4ecd-9750-130e1062176d},...,222.572713,1.891656,1.154787e+06,4309.229346,3,1,Medium,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((62.04155 30.27606, 62.04155 30.28598..."
161,98,FI179,81142,Afghanistan,Nimroz,Chakhansur,{e45f0a88-415f-4ea5-b9e9-9edea5c2930e},Grid cells that are planned but not started,0,{5f7c7d88-b7be-45dc-a4cd-f200dc6c8dd9},...,0.000000,0.000000,1.161728e+06,4323.095516,0,0,Low,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((62.47323 30.85163, 62.47323 30.86154..."
162,99,FM119,83124,Afghanistan,Nimroz,Zaranj,{44d831f1-40a2-455c-ac4d-6a07704ce85c},Grid cells that are planned but not started,0,{350e6501-8c95-458c-b623-ea3d6b27b6ef},...,0.000000,0.000000,1.162168e+06,4323.976180,0,0,Low,nimroz_class_1__nimroz_class,C:/Users/USER/OneDrive - World Health Organiza...,"POLYGON ((61.93363 30.88760, 61.93363 30.89752..."